<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<OutputType>Exe</OutputType>
		<DebugType>embedded</DebugType>
		<PlatformTarget>x64</PlatformTarget>
		<ImplicitUsings>enable</ImplicitUsings>
		<PublishSingleFile>true</PublishSingleFile>
		<SatelliteResourceLanguages>en</SatelliteResourceLanguages>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Eavesdrop" Version="1.3.0" />
		<PackageReference Include="Hypo.Flazzy" Version="0.4.0" />
		<PackageReference Include="Microsoft.Extensions.AI" Version="9.0.1-preview.1.24570.5" />
		<PackageReference Include="Microsoft.Extensions.AI.Ollama" Version="9.0.1-preview.1.24570.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Tanji.Core\Tanji.Core.csproj">
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
		</ProjectReference>
		<ProjectReference Include="..\Tanji.Infrastructure\Tanji.Infrastructure.csproj" />
		<ProjectReference Include="..\Tanji.Core.Generators\Tanji.Core.Generators.csproj" />
	</ItemGroup>

</Project>