<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<DebugType>embedded</DebugType>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<Choose>
		<When Condition="'$(Configuration)' == 'Debug'">
			<ItemGroup>
				<None Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
				<None Include="appsettings.*.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
			</ItemGroup>
		</When>
		<When Condition="'$(Configuration)' == 'Release'">
			<ItemGroup>
				<None Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
			</ItemGroup>
		</When>
	</Choose>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Tanji.Core\Tanji.Core.csproj" />
	</ItemGroup>

</Project>